FROM nginx:latest

MAINTAINER Tejas Rao

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y vim

CMD ["echo":"Git and Vim are installed on the nginx base image"] 

EXPOSE 80